import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Optional: --vault <path> to output directly to an Obsidian vault
const vaultIdx = process.argv.indexOf('--vault');
const vaultDir = vaultIdx > -1 ? process.argv[vaultIdx + 1] : null;

// Determine output directory
const outdir = vaultDir
	? path.join(vaultDir, '.obsidian', 'plugins', 'obsidian-gtd')
	: '.';

const outfile = path.join(outdir, 'main.js');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: prod,
});

// Copy manifest and styles to vault on first build
async function copyAssets() {
	if (vaultDir) {
		fs.cpSync('manifest.json', path.join(outdir, 'manifest.json'), { force: true });
		fs.cpSync('styles.css', path.join(outdir, 'styles.css'), { force: true });
		console.log(`Assets copied to ${outdir}`);
	}
}

if (prod) {
	await context.rebuild();
	process.exit(0);
}

if (vaultDir) {
	await copyAssets();
	console.log(`Watching... output to ${outdir}`);
	await context.watch();
} else {
	// Dev mode, output to current dir
	await context.rebuild();
	process.exit(0);
}
